//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EconnectTMSservice.AccountOpeningRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Incoming/", ConfigurationName="AccountOpeningRef.IncomingTransaction")]
    public interface IncomingTransaction {
        
        // CODEGEN: Generating message contract since element name idnumber from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EconnectTMSservice.AccountOpeningRef.NIDRequestResponse NIDRequest(EconnectTMSservice.AccountOpeningRef.NIDRequest request);
        
        // CODEGEN: Generating message contract since element name session from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EconnectTMSservice.AccountOpeningRef.OpenAccountResponse OpenAccount(EconnectTMSservice.AccountOpeningRef.OpenAccount request);
        
        // CODEGEN: Generating message contract since element name TranDetails from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        EconnectTMSservice.AccountOpeningRef.SelfRegResponse SelfReg(EconnectTMSservice.AccountOpeningRef.SelfReg request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NIDRequest", Namespace="http://Incoming/", Order=0)]
        public EconnectTMSservice.AccountOpeningRef.NIDRequestBody Body;
        
        public NIDRequest() {
        }
        
        public NIDRequest(EconnectTMSservice.AccountOpeningRef.NIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class NIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idnumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phonenumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string session;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string channel;
        
        public NIDRequestBody() {
        }
        
        public NIDRequestBody(string idnumber, string phonenumber, string session, string channel) {
            this.idnumber = idnumber;
            this.phonenumber = phonenumber;
            this.session = session;
            this.channel = channel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NIDRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NIDRequestResponse", Namespace="http://Incoming/", Order=0)]
        public EconnectTMSservice.AccountOpeningRef.NIDRequestResponseBody Body;
        
        public NIDRequestResponse() {
        }
        
        public NIDRequestResponse(EconnectTMSservice.AccountOpeningRef.NIDRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class NIDRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TranResponse;
        
        public NIDRequestResponseBody() {
        }
        
        public NIDRequestResponseBody(string TranResponse) {
            this.TranResponse = TranResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenAccount {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenAccount", Namespace="http://Incoming/", Order=0)]
        public EconnectTMSservice.AccountOpeningRef.OpenAccountBody Body;
        
        public OpenAccount() {
        }
        
        public OpenAccount(EconnectTMSservice.AccountOpeningRef.OpenAccountBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class OpenAccountBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string session;
        
        public OpenAccountBody() {
        }
        
        public OpenAccountBody(string session) {
            this.session = session;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenAccountResponse", Namespace="http://Incoming/", Order=0)]
        public EconnectTMSservice.AccountOpeningRef.OpenAccountResponseBody Body;
        
        public OpenAccountResponse() {
        }
        
        public OpenAccountResponse(EconnectTMSservice.AccountOpeningRef.OpenAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class OpenAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TranResponse;
        
        public OpenAccountResponseBody() {
        }
        
        public OpenAccountResponseBody(string TranResponse) {
            this.TranResponse = TranResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelfReg {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelfReg", Namespace="http://Incoming/", Order=0)]
        public EconnectTMSservice.AccountOpeningRef.SelfRegBody Body;
        
        public SelfReg() {
        }
        
        public SelfReg(EconnectTMSservice.AccountOpeningRef.SelfRegBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SelfRegBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TranDetails;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AuthKey;
        
        public SelfRegBody() {
        }
        
        public SelfRegBody(string TranDetails, string AuthKey) {
            this.TranDetails = TranDetails;
            this.AuthKey = AuthKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelfRegResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelfRegResponse", Namespace="http://Incoming/", Order=0)]
        public EconnectTMSservice.AccountOpeningRef.SelfRegResponseBody Body;
        
        public SelfRegResponse() {
        }
        
        public SelfRegResponse(EconnectTMSservice.AccountOpeningRef.SelfRegResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SelfRegResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TranResponse;
        
        public SelfRegResponseBody() {
        }
        
        public SelfRegResponseBody(string TranResponse) {
            this.TranResponse = TranResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IncomingTransactionChannel : EconnectTMSservice.AccountOpeningRef.IncomingTransaction, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IncomingTransactionClient : System.ServiceModel.ClientBase<EconnectTMSservice.AccountOpeningRef.IncomingTransaction>, EconnectTMSservice.AccountOpeningRef.IncomingTransaction {
        
        public IncomingTransactionClient() {
        }
        
        public IncomingTransactionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IncomingTransactionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IncomingTransactionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IncomingTransactionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EconnectTMSservice.AccountOpeningRef.NIDRequestResponse EconnectTMSservice.AccountOpeningRef.IncomingTransaction.NIDRequest(EconnectTMSservice.AccountOpeningRef.NIDRequest request) {
            return base.Channel.NIDRequest(request);
        }
        
        public string NIDRequest(string idnumber, string phonenumber, string session, string channel) {
            EconnectTMSservice.AccountOpeningRef.NIDRequest inValue = new EconnectTMSservice.AccountOpeningRef.NIDRequest();
            inValue.Body = new EconnectTMSservice.AccountOpeningRef.NIDRequestBody();
            inValue.Body.idnumber = idnumber;
            inValue.Body.phonenumber = phonenumber;
            inValue.Body.session = session;
            inValue.Body.channel = channel;
            EconnectTMSservice.AccountOpeningRef.NIDRequestResponse retVal = ((EconnectTMSservice.AccountOpeningRef.IncomingTransaction)(this)).NIDRequest(inValue);
            return retVal.Body.TranResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EconnectTMSservice.AccountOpeningRef.OpenAccountResponse EconnectTMSservice.AccountOpeningRef.IncomingTransaction.OpenAccount(EconnectTMSservice.AccountOpeningRef.OpenAccount request) {
            return base.Channel.OpenAccount(request);
        }
        
        public string OpenAccount(string session) {
            EconnectTMSservice.AccountOpeningRef.OpenAccount inValue = new EconnectTMSservice.AccountOpeningRef.OpenAccount();
            inValue.Body = new EconnectTMSservice.AccountOpeningRef.OpenAccountBody();
            inValue.Body.session = session;
            EconnectTMSservice.AccountOpeningRef.OpenAccountResponse retVal = ((EconnectTMSservice.AccountOpeningRef.IncomingTransaction)(this)).OpenAccount(inValue);
            return retVal.Body.TranResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EconnectTMSservice.AccountOpeningRef.SelfRegResponse EconnectTMSservice.AccountOpeningRef.IncomingTransaction.SelfReg(EconnectTMSservice.AccountOpeningRef.SelfReg request) {
            return base.Channel.SelfReg(request);
        }
        
        public string SelfReg(string TranDetails, string AuthKey) {
            EconnectTMSservice.AccountOpeningRef.SelfReg inValue = new EconnectTMSservice.AccountOpeningRef.SelfReg();
            inValue.Body = new EconnectTMSservice.AccountOpeningRef.SelfRegBody();
            inValue.Body.TranDetails = TranDetails;
            inValue.Body.AuthKey = AuthKey;
            EconnectTMSservice.AccountOpeningRef.SelfRegResponse retVal = ((EconnectTMSservice.AccountOpeningRef.IncomingTransaction)(this)).SelfReg(inValue);
            return retVal.Body.TranResponse;
        }
    }
}
